Repository Hansung-WebFramework/reaction, pull requests merged in 2024-11, with the labels that each got.

#4 chore : vite, react 초기 세팅
  README.md
  react-app/.gitignore
  react-app/README.md
  react-app/eslint.config.js
  react-app/index.html
  react-app/package-lock.json
  react-app/package.json
  react-app/public/vite.svg
  react-app/src/App.css
  react-app/src/App.jsx
  react-app/src/assets/react.svg
  react-app/src/index.css
  react-app/src/main.jsx
  react-app/vite.config.js
Labels: chore

#6 chore : tailwind css + react router dom
  README.md
  react-app/package-lock.json
  react-app/package.json
  react-app/postcss.config.js
  react-app/src/App.jsx
  react-app/src/index.css
  react-app/src/pages/AboutPage.jsx
  react-app/src/pages/HomePage.jsx
  react-app/tailwind.config.js
Labels: chore

#8 [chore] ci 작성 및 테스트
  .github/workflows/ci.yml
Labels: chore

#19 [design] 온보딩 페이지 퍼블리싱
  .github/workflows/ci.yml
  package-lock.json
  react-app/package-lock.json
  react-app/package.json
  react-app/src/App.css
  react-app/src/App.jsx
  react-app/src/assets/images/OnBoardingObject.png
  react-app/src/components/AnalysisChart.jsx
  react-app/src/components/Header.jsx
  react-app/src/components/Header.module.css
  react-app/src/index.css
  react-app/src/main.jsx
  react-app/src/pages/OnBoardingPage.jsx
  react-app/src/pages/OnBoardingPage.module.css
  react-app/tailwind.config.js
Labels: design

#18 [design] 판별된 기사 목록 페이지 퍼블리싱
  .github/workflows/ci.yml
  react-app/package-lock.json
  react-app/package.json
  react-app/src/App.jsx
  react-app/src/assets/images/IdentifiedArticlesPage1.png
  react-app/src/assets/images/IdentifiedArticlesPage2.png
  react-app/src/assets/images/IdentifiedArticlesPage3.png
  react-app/src/assets/images/IdentifiedArticlesPage4.png
  react-app/src/components/ArticleList.jsx
  react-app/src/components/articles/ArticleItem.jsx
  react-app/src/components/articles/ArticleList.jsx
  react-app/src/components/articles/Pagination.jsx
  react-app/src/components/articles/SelectedArticle.jsx
  react-app/src/components/layout/Header.jsx
  react-app/src/components/layout/Header.module.css
  react-app/src/components/layout/Navbar.jsx
  react-app/src/data/articles.js
  react-app/src/index.css
  react-app/src/pages/IdentifiedArticlesPage.jsx
  react-app/src/pages/OnBoardingPage.jsx
Labels: design

#22 [design] 분석 차트 페이지 퍼블리싱
  package-lock.json
  react-app/src/App.jsx
  react-app/src/assets/images/fakenewsimg.png
  react-app/src/components/AnalysisChart.jsx
  react-app/src/components/layout/AnalysisPage.module.css
  react-app/src/components/layout/Header.jsx
  react-app/src/components/ui/Button.jsx
  react-app/src/components/ui/Card.jsx
  react-app/src/pages/AnalysisPage.jsx
  react-app/src/pages/OnBoardingPage.jsx
Labels: design

#28 [refactor] 분석 차트 페이지 코드 리팩토링
  react-app/src/App.jsx
  react-app/src/pages/AnalysisPage.jsx
Labels: refactor

#31 [chore] 분석 차트 페이지용 mock data 추가
  react-app/src/App.jsx
  react-app/src/data/mockData.js
  react-app/src/pages/AnalysisPage.jsx
Labels: chore

#36 [feat] 판별된 기사 목록 페이지 hover 효과 적용
  react-app/src/App.jsx
  react-app/src/components/articles/ArticleItem.jsx
  react-app/src/pages/AnalysisPage.jsx
Labels: feature
